In [1]:
# import library
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [6]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
209416,Data Engineer,Data Engineer,"Stockholm, Sweden",via Trabajo.org,Full-time,False,Sweden,2023-08-10 22:36:57,False,False,Sweden,None,NaN,NaN,MasterCard,"['sql', 'python', 'sql server', 'hadoop', 'loo...","{'analyst_tools': ['looker', 'tableau'], 'data..."
418718,Software Engineer,Staff Backend Software Engineer | Marketing An...,"Lisbon, Portugal",via Indeed,Full-time,False,Portugal,2023-06-14 16:49:16,False,False,Portugal,None,NaN,NaN,Gympass,"['java', 'scala', 'python', 'ruby', 'ruby', 'j...","{'databases': ['postgresql', 'mysql', 'dynamod..."
306528,Data Engineer,Data Engineer Bilingüe,Anywhere,via LinkedIn,Full-time,True,Mexico,2023-07-26 17:46:48,False,False,Mexico,None,NaN,NaN,axity,"['sql', 'python', 'gcp', 'aws']","{'cloud': ['gcp', 'aws'], 'programming': ['sql..."
198035,Data Analyst,Business Data analyst,"Dallas, TX",via Dice,Contractor,False,"Texas, United States",2023-02-16 15:03:15,True,False,United States,hour,NaN,64.5,Net2Source Inc.,"['sql', 'snowflake']","{'cloud': ['snowflake'], 'programming': ['sql']}"
658483,Data Analyst,Data Analyst | Power Bi,"Madrid, Spain",via LinkedIn,Full-time,False,Spain,2023-06-12 10:32:06,True,False,Spain,None,NaN,NaN,ACCOM,"['sql', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'progra..."

In [8]:
df.index.name = 'job_index'

## Index Reset

In [ ]:
df_indo = df[df['job_country'] == 'Indonesia'] 
df_indo.head(5)

# bisa diliat di df_indo kalau job index nya random

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
643,Data Scientist,Data Scientist,"Bali, Indonesia",via HR Software For Growing Businesses | Fresh...,Full-time,False,Indonesia,2023-07-03 13:14:47,False,False,Indonesia,None,NaN,NaN,Tyrads PTE. LTD.,"['python', 'r', 'aws', 'gcp', 'azure', 'spark'...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
1213,Data Scientist,Data Scientist,Indonesia,via Linkedin,Full-time,False,Indonesia,2023-04-17 13:19:59,False,False,Indonesia,None,NaN,NaN,Robert Walters,"['python', 'sql']","{'programming': ['python', 'sql']}"
1244,Data Engineer,Data Engineer,"Jakarta, Indonesia",via LinkedIn,Full-time,False,Indonesia,2023-08-31 13:44:04,True,False,Indonesia,None,NaN,NaN,JULO,"['sql', 'java', 'python', 'postgresql', 'redsh...","{'cloud': ['redshift', 'aws', 'gcp', 'azure'],..."
1858,Data Engineer,Data Engineer - ETL Developer,"Jakarta, Indonesia",via LinkedIn,Contractor,False,Indonesia,2023-05-29 13:14:42,False,False,Indonesia,None,NaN,NaN,PT. IDStar Cipta Teknologi (IDstar),"['sql', 'oracle', 'spark', 'kafka']","{'cloud': ['oracle'], 'libraries': ['spark', '..."
2048,Senior Data Scientist,Senior Data Scientist,Indonesia,via LinkedIn,Full-time,False,Indonesia,2023-05-25 13:32:17,False,False,Indonesia,None,NaN,NaN,Robert Walters,"['sql', 'python']","{'programming': ['sql', 'python']}"

In [ ]:
# Create new index 
# ini ngereset / delete kolom yang tadinya jadi index 
df_indo.reset_index(inplace=True)

In [ ]:
# new index ada di bagian paling kiri 
df_indo

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,643,Data Scientist,Data Scientist,"Bali, Indonesia",via HR Software For Growing Businesses | Fresh...,Full-time,False,Indonesia,2023-07-03 13:14:47,False,False,Indonesia,None,NaN,NaN,Tyrads PTE. LTD.,"['python', 'r', 'aws', 'gcp', 'azure', 'spark'...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
1,1213,Data Scientist,Data Scientist,Indonesia,via Linkedin,Full-time,False,Indonesia,2023-04-17 13:19:59,False,False,Indonesia,None,NaN,NaN,Robert Walters,"['python', 'sql']","{'programming': ['python', 'sql']}"
2,1244,Data Engineer,Data Engineer,"Jakarta, Indonesia",via LinkedIn,Full-time,False,Indonesia,2023-08-31 13:44:04,True,False,Indonesia,None,NaN,NaN,JULO,"['sql', 'java', 'python', 'postgresql', 'redsh...","{'cloud': ['redshift', 'aws', 'gcp', 'azure'],..."
3,1858,Data Engineer,Data Engineer - ETL Developer,"Jakarta, Indonesia",via LinkedIn,Contractor,False,Indonesia,2023-05-29 13:14:42,False,False,Indonesia,None,NaN,NaN,PT. IDStar Cipta Teknologi (IDstar),"['sql', 'oracle', 'spark', 'kafka']","{'cloud': ['oracle'], 'libraries': ['spark', '..."
4,2048,Senior Data Scientist,Senior Data Scientist,Indonesia,via LinkedIn,Full-time,False,Indonesia,2023-05-25 13:32:17,False,False,Indonesia,None,NaN,NaN,Robert Walters,"['sql', 'python']","{'programming': ['sql', 'python']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2988,785194,Data Analyst,Data Analyst,Indonesia,via Lokersby.id,Full-time,False,Indonesia,2023-07-22 06:46:40,False,False,Indonesia,None,NaN,NaN,PT Istana Mobil Surabaya Indah,None,None
2989,785201,Data Scientist,Data Scientist,"Jakarta, Indonesia",via Trabajo.org,Full-time,False,Indonesia,2023-11-16 06:25:17,False,False,Indonesia,None,NaN,NaN,Great Giant Foods (GGF),"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
2990,785271,Data Analyst,Data Analyst,"Jakarta, Indonesia",via Trabajo.org,Full-time,False,Indonesia,2023-11-25 06:23:43,True,False,Indonesia,None,NaN,NaN,Everwhite Indonesia,None,None
2991,785312,Machine Learning Engineer,Machine Learning Engineer,"Jakarta, Indonesia",via Trabajo.org,Full-time,False,Indonesia,2023-11-25 06:23:43,False,False,Indonesia,None,NaN,NaN,Aliz,"['python', 'sql', 'gcp', 'bigquery', 'airflow'...","{'cloud': ['gcp', 'bigquery'], 'libraries': ['..."
2992,785567,Data Analyst,Data Analyst Intern,"Jakarta, Indonesia",via Trabajo.org,"Full-time, Part-time, and Internship",False,Indonesia,2023-12-07 06:22:51,False,False,Indonesia,None,NaN,NaN,MyEduSolve,"['r', 'java']","{'programming': ['r', 'java']}"

## Set Index

In [35]:
df_indo.set_index('job_index', inplace=True)

In [36]:
df_indo

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
643,Data Scientist,Data Scientist,"Bali, Indonesia",via HR Software For Growing Businesses | Fresh...,Full-time,False,Indonesia,2023-07-03 13:14:47,False,False,Indonesia,None,NaN,NaN,Tyrads PTE. LTD.,"['python', 'r', 'aws', 'gcp', 'azure', 'spark'...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
1213,Data Scientist,Data Scientist,Indonesia,via Linkedin,Full-time,False,Indonesia,2023-04-17 13:19:59,False,False,Indonesia,None,NaN,NaN,Robert Walters,"['python', 'sql']","{'programming': ['python', 'sql']}"
1244,Data Engineer,Data Engineer,"Jakarta, Indonesia",via LinkedIn,Full-time,False,Indonesia,2023-08-31 13:44:04,True,False,Indonesia,None,NaN,NaN,JULO,"['sql', 'java', 'python', 'postgresql', 'redsh...","{'cloud': ['redshift', 'aws', 'gcp', 'azure'],..."
1858,Data Engineer,Data Engineer - ETL Developer,"Jakarta, Indonesia",via LinkedIn,Contractor,False,Indonesia,2023-05-29 13:14:42,False,False,Indonesia,None,NaN,NaN,PT. IDStar Cipta Teknologi (IDstar),"['sql', 'oracle', 'spark', 'kafka']","{'cloud': ['oracle'], 'libraries': ['spark', '..."
2048,Senior Data Scientist,Senior Data Scientist,Indonesia,via LinkedIn,Full-time,False,Indonesia,2023-05-25 13:32:17,False,False,Indonesia,None,NaN,NaN,Robert Walters,"['sql', 'python']","{'programming': ['sql', 'python']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785194,Data Analyst,Data Analyst,Indonesia,via Lokersby.id,Full-time,False,Indonesia,2023-07-22 06:46:40,False,False,Indonesia,None,NaN,NaN,PT Istana Mobil Surabaya Indah,None,None
785201,Data Scientist,Data Scientist,"Jakarta, Indonesia",via Trabajo.org,Full-time,False,Indonesia,2023-11-16 06:25:17,False,False,Indonesia,None,NaN,NaN,Great Giant Foods (GGF),"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
785271,Data Analyst,Data Analyst,"Jakarta, Indonesia",via Trabajo.org,Full-time,False,Indonesia,2023-11-25 06:23:43,True,False,Indonesia,None,NaN,NaN,Everwhite Indonesia,None,None
785312,Machine Learning Engineer,Machine Learning Engineer,"Jakarta, Indonesia",via Trabajo.org,Full-time,False,Indonesia,2023-11-25 06:23:43,False,False,Indonesia,None,NaN,NaN,Aliz,"['python', 'sql', 'gcp', 'bigquery', 'airflow'...","{'cloud': ['gcp', 'bigquery'], 'libraries': ['..."
785567,Data Analyst,Data Analyst Intern,"Jakarta, Indonesia",via Trabajo.org,"Full-time, Part-time, and Internship",False,Indonesia,2023-12-07 06:22:51,False,False,Indonesia,None,NaN,NaN,MyEduSolve,"['r', 'java']","{'programming': ['r', 'java']}"

## Sort Index

In [39]:
median_pivot = df_indo.pivot_table(values ='salary_year_avg', index='job_title_short', aggfunc= ['median', 'min', 'max'])
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  64800.0         50400.0         64800.0
Data Analyst                      77017.5         50400.0        132500.0
Data Engineer                    132910.5         72000.0        147500.0
Data Scientist                    90000.5         50400.0        157500.0
Machine Learning Engineer        115400.0         64800.0        166000.0
Senior Data Analyst              111175.0        109500.0        111175.0
Senior Data Engineer             147500.0        147500.0        147500.0
Senior Data Scientist            118350.0         79200.0        157500.0
Software Engineer                123000.0        123000.0        123000.0

In [ ]:
# by= nya dibikin tuple () karena dia ada 2 baris yaitu salary n agg func
median_pivot.sort_values(by=('median', 'salary_year_avg'), ascending=False)

# median_pivot.sort_values(by=('job_title_short', 'salary_year_avg'), ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Engineer             147500.0        147500.0        147500.0
Data Engineer                    132910.5         72000.0        147500.0
Software Engineer                123000.0        123000.0        123000.0
Senior Data Scientist            118350.0         79200.0        157500.0
Machine Learning Engineer        115400.0         64800.0        166000.0
Senior Data Analyst              111175.0        109500.0        111175.0
Data Scientist                    90000.5         50400.0        157500.0
Data Analyst                      77017.5         50400.0        132500.0
Business Analyst                  64800.0         50400.0         64800.0

In [47]:
# ini sorting dari job title nya 
median_pivot.sort_index(inplace=True)

In [48]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  64800.0         50400.0         64800.0
Data Analyst                      77017.5         50400.0        132500.0
Data Engineer                    132910.5         72000.0        147500.0
Data Scientist                    90000.5         50400.0        157500.0
Machine Learning Engineer        115400.0         64800.0        166000.0
Senior Data Analyst              111175.0        109500.0        111175.0
Senior Data Engineer             147500.0        147500.0        147500.0
Senior Data Scientist            118350.0         79200.0        157500.0
Software Engineer                123000.0        123000.0        123000.0